routes/web.php
<?php
use Intervention\Image\Facades\Image;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::post('login', ['as' => 'login', 'uses' => 'Authentication\AuthenticationController@login']);
Route::get('/', function () {
    return redirect("login");
});
Route::group([
    'prefix' => 'password',
], function () {
    Route::post('reset-request', 'Authentication\AuthenticationController@resetRequest');
    Route::get('find/{token}', 'Authentication\AuthenticationController@find');
    Route::post('reset', 'Authentication\AuthenticationController@reset');
});

$router->group(['middleware' => 'auth'], function () {
    Route::get('home', function () {
        return view('home/home');
    });

    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');

    Route::resource('discount', 'Discount\DiscountController');
    Route::post('discount/search', 'Discount\DiscountController@search');
    Route::get('consumer-sale-limit/{consumer_id}', 'Consumer\ConsumerController@saleLimitonsumer');
    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');
    Route::resource('item/category', 'Item\ItemCategoryController');
    Route::post('item/category/search', 'Item\ItemCategoryController@search');
    Route::resource('item', 'Item\ItemController');
    Route::get('item/search', 'Item\ItemController@search');
    Route::get('item-search', 'Item\ItemController@itemSearch');
    Route::get('item-search-list', 'Item\ItemController@itemSearchList');
    Route::resource('transaction', 'Transaction\TransactionMasterController');
    Route::post('transaction/search', 'Transaction\TransactionMasterController@search');
    Route::resource('demand', 'Demand\DemandMasterController');
    Route::post('demand/search', 'Demand\DemandMasterController@search');
    Route::get('demand-item-search', 'Demand\DemandMasterController@itemSearch');
    Route::get('demand-item-search-list', 'Demand\DemandMasterController@itemSearchList');
    Route::resource('permission', 'Permission\PermissionController');
    Route::resource('user', 'User\UserController');
    Route::post('user-search', 'User\UserController@search');
    Route::get('profile', 'User\UserController@profile');
    Route::post('change-profile-pic', 'User\UserController@updateProfilePic')->name('change-profile-pic');

});

Route::get('login', function () {
    return view('auth/login');
});
Route::get('logout', 'Authentication\AuthenticationController@logout');

Route::get('storage/app/public/profile/{filename}', function ($filename) {
    return Image::make(storage_path('app/public/profile/' . $filename))->response();
});

// policy Routes of consumer
// Route::get('consumer/view', 'ConsumerController@view');
// Route::get('consumer/create', 'ConsumerController@create');
// Route::get('consumer/update', 'ConsumerController@update');
// Route::get('consumer/delete', 'ConsumerController@delete');

app/Discount.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Discount extends Model
{

    protected $fillable = ['consumer_id', 'item_category_id', 'discount_percentage', 'is_active'];
    public function consumer()
    {
        return $this->belongsTo('App\Consumer', 'consumer_id');
    }

    public function itemCategory()
    {
        return $this->belongsTo('App\ItemCategory', 'item_category_id');
    }

}

app/Http/Controllers/Discount/DiscountController.php
<?php

namespace App\Http\Controllers\Discount;

use App\Consumer;
use App\Discount;
use App\Http\Controllers\Controller;
use App\ItemCategory;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use RealRashid\SweetAlert\Facades\Alert;

class DiscountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if ($user->can('view', Discount::class)) {

            $discounts = Discount::with('consumer', 'itemCategory')->latest()->paginate(10);
            return view('Discount.index', compact('discounts'));
        } else {
            return redirect('/');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $user = Auth::user();
        if ($user->can('create', Discount::class)) {
            $consumers = Consumer::where('type', 'dispatcher')->get();

            $item_categories = ItemCategory::all();
            return view('Discount.create', compact('consumers', 'item_categories'));
        } else {
            return redirect('/');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => 'This field is required.',

        ];

        Validator::make($request->all(), [
            'consumer_id' => 'required',
            'item_category_id' => 'required',
            'discount_percentage' => 'required|numeric|between:0,100',
            'is_active' => 'required',
        ], $messages)->validate();
        $discount = Discount::create($request->all());
        Alert::alert('Saved', 'Your Record is saved!', 'success');
        return redirect('discount');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $user = Auth::user();
        if ($user->can('edit', Discount::class)) {
            $discount = Discount::find($id);
            $consumers = Consumer::where('type', 'dispatcher')->get();

            $item_categories = ItemCategory::all();

            return view('discount/edit', compact('discount', 'id', 'consumers', 'item_categories'));
        } else {
            return redirect('/');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $user = Auth::user();
        if ($user->can('update', Discount::class)) {
            $messages = [
                'required' => 'This field is required.',

            ];

            Validator::make($request->all(), [
                'consumer_id' => 'required',
                'item_category_id' => 'required',
                'discount_percentage' => 'required|numeric|between:0,100',
                'is_active' => 'required',
            ], $messages)->validate();
            $discount = Discount::find($id);
            $discount->update($request->all());
            Alert::alert('Update', 'Your Record is Updated!', 'success');
            return redirect('discount');
        } else {
            return redirect('/');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $user = Auth::user();
        if ($user->can('delete', Discount::class)) {
            Discount::destroy($id);

            Alert::alert('Delete', 'Your Record is deleted!', 'success');
            return redirect('discount');
        } else {
            return redirect('/');

        }
    }
    public function search(Request $request)
    {
        $search = \Request::get('search');
        if ($search) {
            $discounts = Discount::with('consumer', 'itemCategory')->where(function ($query) use ($search) {
                $query->where('discount_percentage', 'LIKE', "%$search%")
                    ->orWhere('is_active', 'LIKE', "%$search%")
                    ->orWhereHas('consumer', function ($query) use ($search) {
                        $query->where('name', 'like', '%' . $search . '%');
                    })
                    ->orWhereHas('itemCategory', function ($query) use ($search) {
                        $query->where('name', 'like', '%' . $search . '%');
                    });

            })->latest()->paginate(10);
        } else {
            $discounts = Discount::latest()->paginate(10);

        }
        if ($discounts->count() == 0) {
            $discounts = Discount::latest()->paginate(10);

        }
        return view('Discount.index', ['discounts' => $discounts]);

    }
}

resources/views/Discount/create.blade.php
@extends('layouts.master')
@section('title', 'Create Discount')
@section('content')
<div class="app-title">
        <div>
                <h1><i class="fa fa-edit"></i> Discount</h1>
        </div>
</div>
<form method="post" action="{{action('Discount\DiscountController@store')}}">
        <div class="row">
                <div class="col-md-6">
                        <div class="tile">
                                <h3 class="tile-title">Add Discount Record</h3>
                                <div class="tile-body">
                                        @if($errors->all())
                                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                <strong>Please fix below errors</strong>
                                                <button type="button" class="close" data-dismiss="alert"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                </button>
                                        </div>
                                        @endif
                                        {{csrf_field()}}
                                        <input name="_method" type="hidden" value="POST">
                                        <input type="hidden" value="{{csrf_token()}}" name="_token" />

                                        <div class="form-group">
                                                <label class="control-label">Dispatcher Name</label>
                                                        <select name="consumer_id" class="form-control" value="{{ old('consumer_id') }}" class="{{ $errors->first('consumer_id') != '' ? 'form-control is-invalid' : 'form-control' }}" required>
                                                        <option value="" disabled selected>Please Select Name</option>
                                                         @foreach($consumers as $consumer)
                                                        <option value="{{ $consumer->id}}">{{ $consumer->name}}</option>
                                                        @endforeach
                                                        </select>
                                                @if($errors->first('consumer_id'))
                                                <div class="form-control-feedback">{{ $errors->first('consumer_id') }}
                                                </div>
                                                @endif
                                        </div>
                                        <div class="form-group">
                                                <label class="control-label">Category Name</label>
                                                        <select name="item_category_id" class="form-control" value="{{ old('item_category_id') }}" class="{{ $errors->first('item_category_id') != '' ? 'form-control is-invalid' : 'form-control' }}" required>
                                                        <option value="" disabled selected>Please Select Category Name</option>
                                                         @foreach($item_categories as $category)
                                                        <option value="{{ $category->id}}">{{ $category->name}}</option>
                                                        @endforeach
                                                        </select>
                                                @if($errors->first('item_category_id'))
                                                <div class="form-control-feedback">{{ $errors->first('item_category_id') }}
                                                </div>
                                                @endif
                                        </div>
                                        <div class="form-group">
                                                <label>Discount Percentage</label>
                                                <input class="{{ $errors->first('discount_percentage') != '' ? 'form-control is-invalid' : 'form-control' }}"
                                                        type="text" placeholder="Enter Discount Percentage" name="discount_percentage" value="{{ old('discount_percentage') }}">
                                                @if($errors->first('discount_percentage'))
                                                <div class="form-control-feedback">{{ $errors->first('discount_percentage') }}</div>
                                                @endif
                                        </div>
                                        <div class="form-group">
                                                <div class="animated-radio-button">
                                                        <label>
                                                                <input type="radio" name="is_active" value="Yes"
                                                                        checked="checked">
                                                                <span class="label-text">Active</span>
                                                        </label>
                                                        <label>
                                                                <input type="radio" name="is_active" value="No">
                                                                <span class="label-text">In Active</span>
                                                        </label>
                                                </div>
                                                @if($errors->first('is_active'))
                                                <div class="form-control-feedback">{{ $errors->first('is_active') }}
                                                </div>
                                                @endif
                                        </div>





                                <div class="tile-footer">
                                        <button class="btn btn-primary" type="submit"><i
                                                        class="fa fa-fw fa-lg fa-check-circle"></i>Save Record</button>
                                </div>
                        </div>
                </div>
        </div>
</form>
@endsection
@section('scripts')
<script>
        // In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
//     $('#company_id').select2();
//     $('#account_id').select2();
});
</script>

@endsection

resources/views/Discount/edit.blade.php
@extends('layouts.master')
@section('title', 'Edit Discount')
@section('content')
<div class="app-title">
  <div>
    <h1><i class="fa fa-edit"></i> Discount</h1>
  </div>
</div>
<form method="post" action="{{action('Discount\DiscountController@update', $id)}}">
  <div class="row">
    <div class="col-md-6">
      <div class="tile">
        <h3 class="tile-title">Edit Discount Record</h3>
        <div class="tile-body">
          @if($errors->all())
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Please fix below errors</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          @endif
          {{csrf_field()}}
          <input name="_method" type="hidden" value="PATCH">
          <input type="hidden" value="{{csrf_token()}}" name="_token" />

                                        <div class="form-group">
                                                <label class="control-label">Dispatcher Name</label>
                                                        <select name="consumer_id" class="form-control" value="{{ old('consumer_id') }}" class="{{ $errors->first('consumer_id') != '' ? 'form-control is-invalid' : 'form-control' }}" required>
                                                        <option value="" disabled >Please Select Name</option>
                                                        @if($discount->consumer_id)
              <option value="{{ $discount->consumer->id }}" selected>{{ $discount->consumer->name }}
               </option>
                @endif

                                                      
                                                         @foreach($consumers as $consumer)
                                                        <option value="{{ $consumer->id}}">{{ $consumer->name}}</option>
                                                        @endforeach
                                                        </select>
                                                @if($errors->first('consumer_id'))
                                                <div class="form-control-feedback">{{ $errors->first('consumer_id') }}
                                                </div>
                                                @endif
                                        </div>
                                        <div class="form-group">
                                                <label class="control-label">Category Name</label>
                                                        <select name="item_category_id" class="form-control" value="{{ old('item_category_id') }}" class="{{ $errors->first('item_category_id') != '' ? 'form-control is-invalid' : 'form-control' }}" required>
                                                        <option value="" disabled >Please Select Category Name</option>
                                                       @if($discount->item_category_id)
              <option value="{{ $discount->ItemCategory->id }}" selected>{{ $discount->itemCategory->name }}
@endif

                                                        
                                                         @foreach($item_categories as $category)
                                                        <option value="{{ $category->id}}">{{ $category->name}}</option>
                                                        @endforeach
                                                        </select>
                                                @if($errors->first('item_category_id'))
                                                <div class="form-control-feedback">{{ $errors->first('item_category_id') }}
                                                </div>
                                                @endif
                                        </div>
                                        <div class="form-group">
                                                <label>Discount Percentage</label>
                                                <input class="{{ $errors->first('discount_percentage') != '' ? 'form-control is-invalid' : 'form-control' }}"
                                                        type="text" placeholder="Enter Discount Percentage" name="discount_percentage" value="{{ $discount->discount_percentage }}">
                                                @if($errors->first('discount_percentage'))
                                                <div class="form-control-feedback">{{ $errors->first('discount_percentage') }}</div>
                                                @endif
                                        </div>
                                        <div class="form-group">
            <div class="animated-radio-button">
              <label>
                <input type="radio"  name="is_active" value="Yes"  {{ ($discount->is_active=="Yes") ? "checked" : "" }}>
                <span class="label-text">Active</span>
              </label>
              <label>
                <input type="radio" name="is_active" value="No" {{ ($discount->is_active=="No") ? "checked" : "" }}>
                <span class="label-text">In Active</span>
              </label>
            </div>
            @if($errors->first('is_active'))
            <div class="form-control-feedback">{{ $errors->first('is_active') }}</div>
            @endif
          </div>
        </div>


        <div class="tile-footer">
          <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Update</button>
        </div>
      </div>
    </div>
  </div>
</form>
@endsection
@section('scripts')
<script>
  // In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    // $('#company_id').select2();
    // $('#account_id').select2();
});
</script>
<script>
$(document).ready(function () {
    $('#company_id').on('change', function() {
               jQuery.ajax({
                  url: "{{ url('/api/accounts') }}",
                  method: 'post',
                  data: {
                     company_id: jQuery('#company_id').val()
                  },
                  success: function(result){
                          $('#account_id')
    .find('option')
    .remove()
    .end()
    .append('<option value="">Select an Account</option>')
    .val('');
                        for (var i = 0; i < result.length; ++i) {
                               $("#account_id").append($("<option />").val(result[i].id).text(result[i].description));
                                if(result[i].children_accounts.length){
                                       appendChilds(result[i].children_accounts);
                               }
                        }
                  }});
               });
});
</script>
<script>
     function appendChilds(result){
        for (var a = 0; a < result.length; ++a) {
                               $("#account_id").append($("<option />").val(result[a].id).text(
                                       function(){
                                               for(var j =0; j<result[a].level; j++){
                                                       spaces=spaces+'\xa0\xa0\xa0\xa0';
                                               }
                                                return spaces+''+result[a].code+'-'+result[a].description;
                                       }
                               ));
                               if(result[a].children_accounts.length){
                                       appendChilds(result[a].children_accounts);
                               }
                        }
     }
</script>
@endsection

resources/views/Discount/index.blade.php
@extends('layouts.master')
@section('title', 'Discounts')
@section('search')
<li class="app-search">
  <form action="{{action('Discount\DiscountController@search')}}" method="POST">
    <input type="hidden" value="{{csrf_token()}}" name="_token" />
    <input class="app-search__input" name="search" type="search" placeholder="Search" value="{{ $search ?? '' }}">
    <button class="app-search__button" type="submit"><i class="fa fa-search"></i></button>
  </form>
</li>
@endsection
@section('content')
<div class="app-title">
    <div>
        <h1><i class="fa fa-th-list"></i> Discount</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                @if(session('message'))
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ session('message') }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif

                <div style="float:right; padding: 10px;">
                <a href="{{action('Discount\DiscountController@create')}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-plus"></i> Add
                                    </a>
                                    </div>

                <table class="table table-hover table-bordered" id="sampleTable">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Item Category</th>
                            <th>Discount</th>
                            <th>Active</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (count($discounts) > 0)
                        @foreach ($discounts as $discount)
                        <tr>
                            <td>{{ $discount->consumer->name }}</td>
                            <td>{{$discount->itemCategory->name}} </td>
                            <td>{{ $discount->discount_percentage }}</td>
                            <td>{{ $discount->is_active }}</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a href="{{action('Discount\DiscountController@edit',$discount->id)}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                       <a href="{{ route('discount.destroy', $discount->id) }}"
                                        class="confirmation btn btn-sm btn-danger" data-title="Delete Record"
                                        data-text="Are you sure to delete this record and its associated data? ">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                         @else
                                                <tr>
                                                <td colspan="6" class="text-center">
                                                        No Record Found
                                                </td>
                                                </tr>
                                                @endif
                    </tbody>
                </table>
                {{ $discounts->links() }}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<!-- Page specific javascripts-->
<script>
    jQuery(document).on('click', '.confirmation', function (e) {
    e.preventDefault(); // Prevent the href from redirecting
    var linkURL = $(this).attr("href");
    var _title = $(this).attr("data-title");
    var _text = $(this).attr("data-text");
    warnBeforeRedirect(linkURL, _text, _title);
});

function warnBeforeRedirect(linkURL, _text, _title) {

    swal({
  title: _title,
  text: _text,
  type: "warning",
  icon: "warning",
  dangerMode: true,
  buttons: true,
}).then(function(isConfirm) {
  if(isConfirm){
 var form = $('<form>', {
            'method': 'POST',
            'action': linkURL
        });

        var hiddenInput = $('<input>', {
            'name': '_method',
            'type': 'hidden',
            'value': 'DELETE'
        });

        hiddenToken = $('<input>', {
            'name': '_token',
            'type': 'hidden',
            'value': jQuery('meta[name="csrf-token"]').attr('content')
        });

        form.append(hiddenInput).append(hiddenToken).appendTo('body').submit();
}else {
    swal("Cancelled", "Your record is safe :)", "info");
  }
});
}
</script>
@endsection