routes/web.php
<?php
use Intervention\Image\Facades\Image;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::post('login', ['as' => 'login', 'uses' => 'Authentication\AuthenticationController@login']);
Route::get('/', function () {
    return redirect("login");
});
Route::group([
    'prefix' => 'password',
], function () {
    Route::post('reset-request', 'Authentication\AuthenticationController@resetRequest');
    Route::get('find/{token}', 'Authentication\AuthenticationController@find');
    Route::post('reset', 'Authentication\AuthenticationController@reset');
});

$router->group(['middleware' => 'auth'], function () {
    Route::get('home', function () {
        return view('home/home');
    });

    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');

    Route::resource('discount', 'Discount\DiscountController');
    Route::post('discount/search', 'Discount\DiscountController@search');
    Route::get('consumer-sale-limit/{consumer_id}', 'Consumer\ConsumerController@saleLimitonsumer');
    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');
    Route::resource('item/category', 'Item\ItemCategoryController');
    Route::post('item/category/search', 'Item\ItemCategoryController@search');
    Route::resource('item', 'Item\ItemController');
    Route::get('item/search', 'Item\ItemController@search');
    Route::get('item-search', 'Item\ItemController@itemSearch');
    Route::get('item-search-list', 'Item\ItemController@itemSearchList');
    Route::resource('transaction', 'Transaction\TransactionMasterController');
    Route::post('transaction/search', 'Transaction\TransactionMasterController@search');
    Route::resource('demand', 'Demand\DemandMasterController');
    Route::post('demand/search', 'Demand\DemandMasterController@search');
    Route::get('demand-item-search', 'Demand\DemandMasterController@itemSearch');
    Route::get('demand-item-search-list', 'Demand\DemandMasterController@itemSearchList');
    Route::resource('permission', 'Permission\PermissionController');
    Route::resource('user', 'User\UserController');
    Route::post('user-search', 'User\UserController@search');
    Route::get('profile', 'User\UserController@profile');
    Route::post('change-profile-pic', 'User\UserController@updateProfilePic')->name('change-profile-pic');

});

Route::get('login', function () {
    return view('auth/login');
});
Route::get('logout', 'Authentication\AuthenticationController@logout');

Route::get('storage/app/public/profile/{filename}', function ($filename) {
    return Image::make(storage_path('app/public/profile/' . $filename))->response();
});

// policy Routes of consumer
// Route::get('consumer/view', 'ConsumerController@view');
// Route::get('consumer/create', 'ConsumerController@create');
// Route::get('consumer/update', 'ConsumerController@update');
// Route::get('consumer/delete', 'ConsumerController@delete');

app/Http/Controllers/Transaction/TransactionMasterController.php
<?php

namespace App\Http\Controllers\Transaction;

use App\Consumer;
use App\Http\Controllers\Controller;
use App\TransactionDetail;
use App\TransactionMaster;
use Auth;
use Illuminate\Http\Request;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\Printer;

class TransactionMasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if ($user->can('view', TransactionMaster::class)) {
            $transactions = TransactionMaster::with('consumer')->orderBy('transaction_date', 'desc')->paginate(10);
            return view('transaction.index')->with(['transactions' => $transactions]);
        } else {
            return redirect('/');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if ($user->can('create', TransactionMaster::class)) {

            $dispatchers = Consumer::where('type', 'dispatcher')->get();
            $suppliers = Consumer::where('type', 'supplier')->get();
            $lastChallanNo = TransactionMaster::where('type', 'sale')->orderBy('created_at', 'DESC')->first();
            if (!empty($lastChallanNo)) {
                $challan_no = $lastChallanNo->receipt_no;
                ++$challan_no;
            } else {
                $challan_no = 10;
            }
            return view('transaction.create')->with(['challanNo' => $challan_no, 'dispatchers' => $dispatchers, 'suppliers' => $suppliers]);
        } else {
            return redirect('/');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user_name = strtoUpper(\Auth::user()->name);
        $Item_Ids_Arr = array_filter($request->item_id, function ($value) {
            return !is_null($value);
        });

        $Item_Codes_Arr = array_filter($request->item_code, function ($value) {
            return !is_null($value);
        });

        $Item_Names_Arr = array_filter($request->item_name, function ($value) {
            return !is_null($value);
        });

        $Item_Rates_Arr = array_filter($request->item_rate, function ($value) {
            return !is_null($value);
        });

        $Each_Item_Total_Discount_Amount_Arr = array_filter($request->total_discount_amount, function ($value) {

            return !is_null($value) && $value > 0;
        });
        $Item_Quantities_Arr = array_filter($request->item_quantity, function ($value) {
            return !is_null($value);
        });

        $Discount_Percentages_Arr = array_filter($request->discount_percentage, function ($value) {
            return !is_null($value);
        });

        $Discounts_Arr = array_filter($request->discount_amount, function ($value) {
            return !is_null($value);
        });

        $Each_Item_Total_Amount_Arr = array_filter($request->total_amt, function ($value) {
            return !is_null($value) && $value > 0;
        });

        if ($request->type == "sale") {
            $consumer_id = $request->dispatcher_id;
            $remark = $request->remark1;
        } else {
            $consumer_id = $request->supplier_id;
            $remark = $request->remark2;
        }
        if (empty($request->return_ind)) {
            $request->return_ind = "N";
        }

        $TransactionMaster = TransactionMaster::create(
            [

                "transaction_date" => $request->transaction_date,
                "type" => $request->type,
                "consumer_id" => $consumer_id,
                "receipt_no" => $request->receipt_no,
                "remark" => $remark,
                "driver_name" => $request->driver_name,
                "van_no" => $request->van_no,
                "supplier_ref_no" => $request->supplier_ref_no,
                "serial_no" => $request->serial_no,
                "return_ind" => $request->return_ind,
            ]
        );

        $length = count($Each_Item_Total_Discount_Amount_Arr);
        for ($i = 0; $i < $length; $i++) {

            $TransactionDetail = TransactionDetail::create(
                [
                    "transaction_master_id" => $TransactionMaster->id,
                    "item_id" => $Item_Ids_Arr[$i],
                    "total_amount" => $Each_Item_Total_Discount_Amount_Arr[$i],
                    "item_quantity" => $Item_Quantities_Arr[$i],
                    "item_rate" => $Item_Rates_Arr[$i],
                    "item_discount_percentage" => $Discount_Percentages_Arr[$i],

                ]
            );

        }
        $date = date_create($request->transaction_date);
        if ($request->type == "sale") {
            try {
                // Enter the share name for your USB printer here
                $connector = new WindowsPrintConnector("citizen");
                /* Print a "Hello world" receipt" */
                $printer = new Printer($connector);
                for ($k = 0; $k < 2; $k++) {
                    $printer->setFont(Printer::FONT_B);
                    $printer->setJustification(Printer::JUSTIFY_CENTER);
                    $printer->selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
                    $printer->setEmphasis(true);
                    $printer->feed();
                    $printer->text("Delivery Challan\n");
                    $printer->selectPrintMode();
                    $printer->setEmphasis(false);
                    $printer->text("_____________________________________________\n");
                    $printer->setJustification(Printer::JUSTIFY_CENTER);
                    $printer->setEmphasis(true);
                    $printer->text(str_pad($request->receipt_no, 0) . "\n");
                    $printer->setJustification(Printer::JUSTIFY_LEFT);
                    $printer->text(str_pad(" ", 18) . '' . str_pad("Voucher Info ", 25) . "\n\n");
                    $printer->text(str_pad(" ", 18) . '' . str_pad("Bilal Ghalib ", 25) . "\n");

                    $printer->setEmphasis(false);
                    $printer->text(str_pad(" ", 12) . '' . str_pad("Date:" . "  " . date_format($date, "d-M-y"), 30) . "\n");
                    $printer->text(str_pad(" ", 17) . '' . str_pad("Operator:" . "  " . strtoUpper($user_name), 30) . "\n");
                    $printer->text(str_pad(" ", 12) . '' . str_pad("Driver:" . "  " . strtoUpper($request->driver_name), 30) . "\n");
                    $printer->text(str_pad(" ", 17) . '' . str_pad("Vehicle #:" . "  " . strtoUpper($request->van_no), 30) . "\n");
                    $printer->feed();
                    $printer->setEmphasis(true);
                    $printer->text(str_pad("Item", 20) . '' . str_pad("Rate", 10) . '' . str_pad("Qty", 9) . ' ' . "Amount" . "\n");
                    $printer->setJustification(Printer::JUSTIFY_CENTER);
                    $printer->text("_____________________________________________\n");
                    $printer->setEmphasis(false);
                    $printer->setTextSize(1, 1);
                    for ($i = 0; $i < $length; $i++) {
                        $printer->setJustification(Printer::JUSTIFY_LEFT);
                        $printer->text(str_pad(substr($Item_Names_Arr[$i], 0, 19), 20) . '' . str_pad($Item_Rates_Arr[$i], 10) . '' . str_pad($Item_Quantities_Arr[$i], 9) . '' . $Each_Item_Total_Amount_Arr[$i] . "\n");

                        if (!empty(substr($Item_Names_Arr[$i], 24))) {
                            $printer->text(str_pad(substr($Item_Names_Arr[$i], 19), 20) . "\n");
                        }
                        if ($i < $length - 1) {
                            $printer->setJustification(Printer::JUSTIFY_CENTER);
                            $printer->text("_____________________________________________\n");
                        }
                    }
                    $printer->setTextSize(1, 1);
                    $printer->setJustification(Printer::JUSTIFY_CENTER);
                    $printer->text("_____________________________________________\n");
                    $printer->setJustification(Printer::JUSTIFY_LEFT);
                    $printer->text(str_pad("Total Items: " . $length, 25) . '' . str_pad("Total Amount: " . $request->sum_total_amount, 23));

                    $printer->text(str_pad(" ", 10) . '' . str_pad("Total Payable Amount: " . round($request->total_payable_amount), 30) . "\n");
                    $printer->setJustification(Printer::JUSTIFY_CENTER);
                    $printer->text("_____________________________________________\n");

                    $printer->setJustification(Printer::JUSTIFY_LEFT);
                    $printer->setEmphasis(true);

                    $printer->setTextSize(1, 1);
                    $printer->text(str_pad("Web: www.doce.pk", 20) . '' . str_pad("Helpine: +92 311 111 3623", 26));

                    $printer->feed();
                    $printer->cut();

                    /* Close printer */
                    $printer->close();
                }
            } catch (Exception $e) {

                echo "Couldn't print to this printer: " . $e->getMessage() . "\n";
            }
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        if ($user->can('edit', TransactionMaster::class)) {

resources/views/Transaction/index.blade.php
@extends('layouts.master')
@section('title', 'Transaction')
@section('search')
<li class="app-search">
  <form action="{{action('Transaction\TransactionMasterController@search')}}" method="POST">
    <input type="hidden" value="{{csrf_token()}}" name="_token" />
    <input class="app-search__input" name="search" type="search" placeholder="Search" value="{{ $search ?? '' }}">
    <button class="app-search__button" type="submit"><i class="fa fa-search"></i></button>
  </form>
</li>
@endsection
@section('content')
<div class="app-title">
    <div>
        <h1><i class="fa fa-th-list"></i> Transactions</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                @if(session('message'))
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ session('message') }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif

                <div style="float:right; padding: 10px;">
                <a href="{{action('Transaction\TransactionMasterController@create')}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-plus"></i> Add
                                    </a>
                                    </div>

                <table class="table table-hover table-bordered" id="sampleTable">
                    <thead>
                        <tr>
                            <th>Consumer Name</th>
                            <th>Transaction Type</th>
                            <th>Challan\GRN#</th>
                            <th>Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (count($transactions) > 0)
                        @foreach ($transactions as $transaction)
                        <tr>
                            <td>{{ $transaction->consumer->name }}</td>
                            <td>{{$transaction->type}} </td>
                            <td>{{$transaction->receipt_no }}</td>
                            <td>{{ $transaction->transaction_date }}</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a href="{{action('Transaction\TransactionMasterController@edit',$transaction->id)}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                    <a href="{{ route('transaction.destroy',$transaction->id) }}"
                                        class="confirmation btn btn-sm btn-danger" data-title="Delete Record"
                                        data-text="Are you sure to delete this record and its associated data? ">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                         @else
                                                <tr>
                                                <td colspan="6" class="text-center">
                                                        No Record Found
                                                </td>
                                                </tr>
                                                @endif
                    </tbody>
                </table>
                {{ $transactions->links() }}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<!-- Page specific javascripts-->
<script>
    jQuery(document).on('click', '.confirmation', function (e) {
    e.preventDefault(); // Prevent the href from redirecting
    var linkURL = $(this).attr("href");
    var _title = $(this).attr("data-title");
    var _text = $(this).attr("data-text");
    warnBeforeRedirect(linkURL, _text, _title);
});

function warnBeforeRedirect(linkURL, _text, _title) {

    swal({
  title: _title,
  text: _text,
  type: "warning",
  icon: "warning",
  dangerMode: true,
  buttons: true,
}).then(function(isConfirm) {
  if(isConfirm){
 var form = $('<form>', {
            'method': 'POST',
            'action': linkURL
        });

        var hiddenInput = $('<input>', {
            'name': '_method',
            'type': 'hidden',
            'value': 'DELETE'
        });

        hiddenToken = $('<input>', {
            'name': '_token',
            'type': 'hidden',
            'value': jQuery('meta[name="csrf-token"]').attr('content')
        });

        form.append(hiddenInput).append(hiddenToken).appendTo('body').submit();
}else {
    swal("Cancelled", "Your record is safe :)", "info");
  }
});
}
</script>
@endsection