routes/web.php
<?php
use Intervention\Image\Facades\Image;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::post('login', ['as' => 'login', 'uses' => 'Authentication\AuthenticationController@login']);
Route::get('/', function () {
    return redirect("login");
});
Route::group([
    'prefix' => 'password',
], function () {
    Route::post('reset-request', 'Authentication\AuthenticationController@resetRequest');
    Route::get('find/{token}', 'Authentication\AuthenticationController@find');
    Route::post('reset', 'Authentication\AuthenticationController@reset');
});

$router->group(['middleware' => 'auth'], function () {
    Route::get('home', function () {
        return view('home/home');
    });

    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');

    Route::resource('discount', 'Discount\DiscountController');
    Route::post('discount/search', 'Discount\DiscountController@search');
    Route::get('consumer-sale-limit/{consumer_id}', 'Consumer\ConsumerController@saleLimitonsumer');
    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');
    Route::resource('item/category', 'Item\ItemCategoryController');
    Route::post('item/category/search', 'Item\ItemCategoryController@search');
    Route::resource('item', 'Item\ItemController');
    Route::get('item/search', 'Item\ItemController@search');
    Route::get('item-search', 'Item\ItemController@itemSearch');
    Route::get('item-search-list', 'Item\ItemController@itemSearchList');
    Route::resource('transaction', 'Transaction\TransactionMasterController');
    Route::post('transaction/search', 'Transaction\TransactionMasterController@search');
    Route::resource('demand', 'Demand\DemandMasterController');
    Route::post('demand/search', 'Demand\DemandMasterController@search');
    Route::get('demand-item-search', 'Demand\DemandMasterController@itemSearch');
    Route::get('demand-item-search-list', 'Demand\DemandMasterController@itemSearchList');
    Route::resource('permission', 'Permission\PermissionController');
    Route::resource('user', 'User\UserController');
    Route::post('user-search', 'User\UserController@search');
    Route::get('profile', 'User\UserController@profile');
    Route::post('change-profile-pic', 'User\UserController@updateProfilePic')->name('change-profile-pic');

});

Route::get('login', function () {
    return view('auth/login');
});
Route::get('logout', 'Authentication\AuthenticationController@logout');

Route::get('storage/app/public/profile/{filename}', function ($filename) {
    return Image::make(storage_path('app/public/profile/' . $filename))->response();
});

// policy Routes of consumer
// Route::get('consumer/view', 'ConsumerController@view');
// Route::get('consumer/create', 'ConsumerController@create');
// Route::get('consumer/update', 'ConsumerController@update');
// Route::get('consumer/delete', 'ConsumerController@delete');

app/Http/Controllers/Demand/DemandMasterController.php
<?php

namespace App\Http\Controllers\Demand;

use App\Consumer;
use App\DemandDetail;
use App\DemandMaster;
use App\Http\Controllers\Controller;
use App\Item;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class DemandMasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();

        if ($user->can('view', DemandMaster::class)) {
            $demands = DemandMaster::with('consumer')->orderBy('demand_date', 'desc')->paginate(10);
            return view('demand.index')->with(['demands' => $demands]);
        } else {
            return redirect("/home");
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if ($user->can('create', DemandMaster::class)) {
            $dispatchers = Consumer::where('type', 'dispatcher')->get();

            $lastDemandNo = DemandMaster::OrderBy('created_at', 'DESC')->first();
            if (!empty($lastDemandNo)) {
                $demand_no = $lastDemandNo->demand_no;
                ++$demand_no;
            } else {
                $demand_no = 11;
            }
            return view('demand.create')->with(['demandNo' => $demand_no, 'dispatchers' => $dispatchers]);
        } else {
            return redirect("/home");
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $messages = [
            'required' => 'This field is required.',
        ];

        Validator::make($request->all(), [
            'consumer_id' => 'required',
            'demand_no' => 'required',
            'demand_date' => 'required',
            'shift' => 'required',
        ], $messages)->validate();
        $Item_Ids_Arr = array_filter($request->item_id, function ($value) {
            return !is_null($value);
        });

        $Item_Codes_Arr = array_filter($request->item_code, function ($value) {
            return !is_null($value);
        });

        $Item_Names_Arr = array_filter($request->item_name, function ($value) {
            return !is_null($value);
        });

        $Item_Quantities_Arr = array_filter($request->item_quantity, function ($value) {
            return !is_null($value);
        });

        $Demand_type_Arr = array_filter($request->demand_type, function ($value) {
            return !is_null($value);
        });

        $DemandMaster = DemandMaster::Create(
            [

                "demand_date" => $request->demand_date,
                "consumer_id" => $request->consumer_id,
                "demand_no" => $request->demand_no,
                "remarks" => $request->remark,
                "shift" => $request->shift,
                "person_name" => $request->person_name,

            ]
        );

        $length = count($Item_Quantities_Arr);
        for ($i = 0; $i < $length; $i++) {

            $DemandDetail = DemandDetail::create(
                [
                    "demand_master_id" => $DemandMaster->id,
                    "item_id" => $Item_Ids_Arr[$i],
                    "quantity" => $Item_Quantities_Arr[$i],
                    "demand_type" => $Demand_type_Arr[$i],

                ]
            );

        }
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        if ($user->can('edit', DemandMaster::class)) {
            $dispatchers = Consumer::where('type', 'dispatcher')->get();

            $demandMaster = DemandMaster::with('consumer')->where('id', $id)->first();

            $demandDetails = DemandDetail::with('item.itemCategory')->where('demand_master_id', $demandMaster->id)->get();

            return view('demand.edit')->with(['demandMaster' => $demandMaster, 'demandDetails' => $demandDetails, 'dispatchers' => $dispatchers, 'id' => $id]);
        } else {
            return redirect("/home");
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = Auth::user();
        if ($user->can('update', DemandMaster::class)) {
            $messages = [
                'required' => 'This field is required.',
            ];

            Validator::make($request->all(), [
                'consumer_id' => 'required',
                'demand_no' => 'required',
                'demand_date' => 'required',
                'shift' => 'required',
            ], $messages)->validate();

            $Item_Ids_Arr = array_filter($request->item_id, function ($value) {
                return !is_null($value);
            });
            $Ids_Arr = array_filter($request->id, function ($value) {
                return !is_null($value);
            });

            $Item_Codes_Arr = array_filter($request->item_code, function ($value) {
                return !is_null($value);
            });

            $Item_Names_Arr = array_filter($request->item_name, function ($value) {
                return !is_null($value);
            });
            $Item_Quantities_Arr = array_filter($request->item_quantity, function ($value) {
                return !is_null($value);
            });

            $Demand_type_Arr = array_filter($request->demand_type, function ($value) {
                return !is_null($value);
            });

            $demandMaster = DemandMaster::Where('id', $id)->update(
                [

                    "demand_date" => $request->demand_date,
                    "consumer_id" => $request->consumer_id,
                    "demand_no" => $request->demand_no,
                    "remarks" => $request->remark,
                    "shift" => $request->shift,
                    "person_name" => $request->person_name,
                ]
            );

            $length = count($Item_Quantities_Arr);
            for ($i = 0; $i < $length; $i++) {
                if ($Ids_Arr[$i] != 0) {
                    $demandDetail = DemandDetail::where(["demand_master_id" => $id, 'id' => $Ids_Arr[$i]])->update(
                        [

                            "item_id" => $Item_Ids_Arr[$i],
                            "quantity" => $Item_Quantities_Arr[$i],
                            "demand_type" => $Demand_type_Arr[$i],

                        ]
                    );
                } else {
                    $demandDetail = DemandDetail::create(
                        [
                            "demand_master_id" => $id,
                            "item_id" => $Item_Ids_Arr[$i],
                            "quantity" => $Item_Quantities_Arr[$i],
                            "demand_type" => $Demand_type_Arr[$i],

                        ]
                    );
                }
            }
            return redirect()->back();
        } else {
            return redirect("/home");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();
        if ($user->can('delete', DemandMaster::class)) {
            DemandMaster::destroy($id);
            \Alert::alert('Delete', 'Your Record is deleted!', 'success');
            return redirect('demand');
        } else {
            return redirect("/home");
        }
    }

    public function search()
    {
        $search = \Request::get('search');
        if ($search) {
            $demands = DemandMaster::with('consumer')->

                orderBy('demand_date', 'desc')
                ->where(function ($query) use ($search) {
                    $query->where('shift', 'LIKE', "%$search%")
                        ->orWhere('demand_no', 'LIKE', "%$search%")
                        ->orWhere('demand_date', 'LIKE', "%$search%")

                        ->orWhereHas('consumer', function ($query) use ($search) {
                            $query->where('name', 'LIKE', "%$search%");
                        });

                })->paginate(10);
        } else {
            $demands = DemandMaster::with('consumer')->orderBy('demand_date', 'desc')->paginate(10);

        }
        return view('demand.index')->with(['demands' => $demands]);
    }

    public function itemSearch(Request $request)
    {

        $search = \Request::get('item_name');

        if ($search) {

            $items = Item::With('itemCategory')->

                where(function ($query) use ($search) {
                $query->where('name', "$search")
                    ->orWhere('item_code', "$search")
                    ->orWhere('barcode_txt', "$search")
                    ->orWhereHas('itemCategory', function ($query) use ($search) {
                        $query->where('name', "$search");
                    });

            })->limit(300)->get();

            if ($items->count()) {

                $length = $items->count();
                return response()->json(['items' => $items, 'length' => $length], 200);
            } else {
                $items = Item::With('itemCategory')->

                    where(function ($query) use ($search) {
                    $query->where('name', "LIKE", "%$search%")

resources/views/Demand/index.blade.php
@extends('layouts.master')
@section('title', 'Demand')
@section('search')
<li class="app-search">
  <form action="{{action('Demand\DemandMasterController@search')}}" method="POST">
    <input type="hidden" value="{{csrf_token()}}" name="_token" />
    <input class="app-search__input" name="search" type="search" placeholder="Search" value="{{ $search ?? '' }}">
    <button class="app-search__button" type="submit"><i class="fa fa-search"></i></button>
  </form>
</li>
@endsection
@section('content')
<div class="app-title">
    <div>
        <h1><i class="fa fa-th-list"></i>Demand</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                @if(session('message'))
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ session('message') }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif

                <div style="float:right; padding: 10px;">
                <a href="{{action('Demand\DemandMasterController@create')}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-plus"></i> Add
                                    </a>
                                    </div>

                <table class="table table-hover table-bordered" id="sampleTable">
                    <thead>
                        <tr>
                            <th>Dispatcher Name</th>
                            <th>Person Name</th>
                            <th>Shift</th>
                            <th>Demand No.</th>
                            <th>Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (count($demands) > 0)
                        @foreach ($demands as $demand)
                        <tr>
                            <td>{{ $demand->consumer->name }}</td>
                            <td>{{ $demand->person_name }}</td>
                            <td>{{$demand->shift}} </td>
                            <td>{{$demand->demand_no }}</td>
                            <td>{{ $demand->demand_date }}</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a href="{{action('Demand\DemandMasterController@edit',$demand->id)}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                    <a href="{{ route('demand.destroy',$demand->id) }}"
                                        class="confirmation btn btn-sm btn-danger" data-title="Delete Record"
                                        data-text="Are you sure to delete this record and its associated data? ">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                         @else
                                                <tr>
                                                <td colspan="6" class="text-center">
                                                        No Record Found
                                                </td>
                                                </tr>
                                                @endif
                    </tbody>
                </table>
                {{ $demands->links() }}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<!-- Page specific javascripts-->
<script>
    jQuery(document).on('click', '.confirmation', function (e) {
    e.preventDefault(); // Prevent the href from redirecting
    var linkURL = $(this).attr("href");
    var _title = $(this).attr("data-title");
    var _text = $(this).attr("data-text");
    warnBeforeRedirect(linkURL, _text, _title);
});

function warnBeforeRedirect(linkURL, _text, _title) {

    swal({
  title: _title,
  text: _text,
  type: "warning",
  icon: "warning",
  dangerMode: true,
  buttons: true,
}).then(function(isConfirm) {
  if(isConfirm){
 var form = $('<form>', {
            'method': 'POST',
            'action': linkURL
        });

        var hiddenInput = $('<input>', {
            'name': '_method',
            'type': 'hidden',
            'value': 'DELETE'
        });

        hiddenToken = $('<input>', {
            'name': '_token',
            'type': 'hidden',
            'value': jQuery('meta[name="csrf-token"]').attr('content')
        });

        form.append(hiddenInput).append(hiddenToken).appendTo('body').submit();
}else {
    swal("Cancelled", "Your record is safe :)", "info");
  }
});
}
</script>
@endsection