routes/web.php
<?php
use Intervention\Image\Facades\Image;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::post('login', ['as' => 'login', 'uses' => 'Authentication\AuthenticationController@login']);
Route::get('/', function () {
    return redirect("login");
});
Route::group([
    'prefix' => 'password',
], function () {
    Route::post('reset-request', 'Authentication\AuthenticationController@resetRequest');
    Route::get('find/{token}', 'Authentication\AuthenticationController@find');
    Route::post('reset', 'Authentication\AuthenticationController@reset');
});

$router->group(['middleware' => 'auth'], function () {
    Route::get('home', function () {
        return view('home/home');
    });

    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');

    Route::resource('discount', 'Discount\DiscountController');
    Route::post('discount/search', 'Discount\DiscountController@search');
    Route::get('consumer-sale-limit/{consumer_id}', 'Consumer\ConsumerController@saleLimitonsumer');
    Route::resource('consumer', 'Consumer\ConsumerController');
    Route::post('customer/search', 'Consumer\ConsumerController@search');
    Route::resource('item/category', 'Item\ItemCategoryController');
    Route::post('item/category/search', 'Item\ItemCategoryController@search');
    Route::resource('item', 'Item\ItemController');
    Route::get('item/search', 'Item\ItemController@search');
    Route::get('item-search', 'Item\ItemController@itemSearch');
    Route::get('item-search-list', 'Item\ItemController@itemSearchList');
    Route::resource('transaction', 'Transaction\TransactionMasterController');
    Route::post('transaction/search', 'Transaction\TransactionMasterController@search');
    Route::resource('demand', 'Demand\DemandMasterController');
    Route::post('demand/search', 'Demand\DemandMasterController@search');
    Route::get('demand-item-search', 'Demand\DemandMasterController@itemSearch');
    Route::get('demand-item-search-list', 'Demand\DemandMasterController@itemSearchList');
    Route::resource('permission', 'Permission\PermissionController');
    Route::resource('user', 'User\UserController');
    Route::post('user-search', 'User\UserController@search');
    Route::get('profile', 'User\UserController@profile');
    Route::post('change-profile-pic', 'User\UserController@updateProfilePic')->name('change-profile-pic');

});

Route::get('login', function () {
    return view('auth/login');
});
Route::get('logout', 'Authentication\AuthenticationController@logout');

Route::get('storage/app/public/profile/{filename}', function ($filename) {
    return Image::make(storage_path('app/public/profile/' . $filename))->response();
});

// policy Routes of consumer
// Route::get('consumer/view', 'ConsumerController@view');
// Route::get('consumer/create', 'ConsumerController@create');
// Route::get('consumer/update', 'ConsumerController@update');
// Route::get('consumer/delete', 'ConsumerController@delete');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'image', 'email', 'enable', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the companies for the user.
     */
    public function companies()
    {
        return $this->hasMany('App\Company');
    }
    public function permission()
    {
        return $this->belongsToMany('App\Permission');
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use Alert;
use App\Http\Controllers\Controller;
use App\Permission;
use App\User;
use DB;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Image;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if ($user->can('view', User::class)) {

            $users = User::latest()->paginate(10);
            return view('user.index', compact('users'));
        } else {
            return redirect('/');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if ($user->can('create', User::class)) {
            $permissions = Permission::all();
            return view('user.create', compact('permissions'));
        } else {
            return redirect('/');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => 'This field is required.',

        ];

        Validator::make($request->all(), [
            'name' => 'required',

            'email' => 'required|unique:users',
            'password' => 'required',
            'enable' => 'required',

        ], $messages)->validate();
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->enable = $request->enable;
        $user->save();
        if ($user->save()) {
            $user->permission()->attach($request->title);

        }
        return redirect('user');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        if ($user->can('edit', User::class)) {
            $permissions = Permission::all();

            $user = User::find($id);
            $user_permissions = $user->permission;
            $user_permission_ids = $user_permissions->pluck('id')->toArray();
            if ($user_permissions->count()) {
                foreach ($permissions as $user_permission) {
                    if (in_array($user_permission->id, $user_permission_ids)) {
                        $user_permission->status = true;

                    } else {
                        $user_permission->status = false;

                    }

                }
                return view('user/edit', compact('user', 'id', 'permissions'));

            }

            return view('user/edit', compact('user', 'id', 'permissions'));

        } else {
            return redirect('/');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find((int) request()->segment(2));
        $messages = [
            'required' => 'This field is required.',
            'unique' => 'This field must be unique.',
        ];

        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'email' => 'required|max:255|unique:companies,email,' . $user->id,
        ], $messages);
        if ($request->password && $request->confirm_password == $request->password) {
            $user->name = $request->name;
            $user->password = Hash::make($request->password);
            $user->save();
            Auth::logout();
            Alert::alert('Updated', 'Your profile is updated & please relogin.', 'success');
            return redirect('login');

        } else {
            $user->name = $request->name;
            $user->save();
            Alert::alert('Updated', 'Your profile is updated', 'success');
            return redirect('profile');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();
        if ($user->can('delete', User::class)) {
            $user = User::find($id);
            $user_permission = $user->permission;

            if ($user_permission->count()) {
                $user = User::destroy($id);
                if ($user) {
                    DB::table("permission_user")->where('user_id', $id)->delete();

                }

            } else {
                $user = User::destroy($id);

            }
            return redirect('user')
                ->with('success', 'User deleted successfully');

        } else {
            return redirect('/');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function profile()
    {
        return view('user.profile');
    }

    public function updateProfilePic(Request $request)
    {
        $image = time() . rand(1, 100) . '.' . explode('/', explode(':', substr($request->image, 0, strpos($request->image, ';')))[1])[1];
        $path = "app/public/profile/";
        $location = storage_path($path . $image);
        Image::make($request->image)->save($location);

        $user = Auth::user();
        $del_image_location = storage_path("app/public/profile/" . $user->image);
        if (File::exists($del_image_location)) {
            File::delete($del_image_location);
        }

        $user->image = $image;
        $user->save();

    }
    public function search(Request $request)
    {
        $search = \Request::get('search');
        if ($search) {
            $users = User::where(function ($query) use ($search) {
                $query->where('name', 'LIKE', "%$search%")
                    ->orWhere('email', 'LIKE', "%$search%");
            })->paginate(10);
        } else {
            $users = User::latest()->paginate(10);
        }
        return view('user.index', ['users' => $users, 'search' => $search]);

    }
}

resources/views/user/create.blade.php
@extends('layouts.master')
@section('content')
<div class="app-title">
        <div>
                <h1><i class="fa fa-edit"></i> Permissions</h1>
        </div>
</div>
<form method="post" action="{{action('User\UserController@store')}}">
        <div class="row">
                <div class="col-md-6">
                        <div class="tile">
                                <h3 class="tile-title">Add Permission</h3>
                                <div class="tile-body">
                                        @if($errors->all())
                                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                <strong>Please fix below errors</strong>
                                                <button type="button" class="close" data-dismiss="alert"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                </button>
                                        </div>
                                        @endif
                                        {{csrf_field()}}
                                        <input name="_method" type="hidden" value="POST">
                                        <input type="hidden" value="{{csrf_token()}}" name="_token" />

                                        <div class="form-group">
                                                <label class="control-label">Name</label>
                                                <input class="{{ $errors->first('name') != '' ? 'form-control is-invalid' : 'form-control' }}"
                                                        type="text" placeholder="Enter User Name"
                                                        name="name" value="{{ old('name') }}" required>
                                                @if($errors->first('name'))
                                                <div class="form-control-feedback">{{ $errors->first('name') }}
                                                </div>
                                                @endif
                                        </div>

                      <div class="form-group">
                        <label class="control-label">Email</label>
                        <input class="{{ $errors->first('email') != '' ? 'form-control is-invalid' : 'form-control' }}" type="email"
                                 placeholder="Email" autofocus name="email" value="{{ old('email') }}" required>
                              @if($errors->first('email'))
                                 <div class="form-control-feedback">{{ $errors->first('email') }}</div>
                                   @endif
                            </div>
                            </div>

                                        <div class="form-group">
                                                <label class="control-label">Password</label>
                                                <input class="{{ $errors->first('password') != '' ? 'form-control is-invalid' : 'form-control' }}"
                                                        type="text" placeholder="Enter User Password"
                                                        name="password" value="{{ old('password') }}" required>
                                                @if($errors->first('password'))
                                                <div class="form-control-feedback">{{ $errors->first('password') }}
                                                </div>
                                                @endif
                                        </div>

                                        <div class="form-group">
                                                <label class="control-label">Login Enable</label>
                                                <select class="js-example-basic-single js-states form-control" name="enable" id="enable"
                                                        >
                                                        <option value="" disabled>Select Login  </option>
                                                        <option value="Yes">Yes</option>
                                                        <option value="No">No</option>

                                                </select>
                                                @if($errors->first('enable'))
                                                <div class="form-control-feedback">{{ $errors->first('enable') }}
                                                </div>
                                                @endif
                                        </div>


                                          <div class="form-group ">
                                                <input type="checkbox" name="select-all" id="select-all" />

                                                <label id="select" style="font-weight: bold;" class="control-label">Select All Permissions</label>
                                                <label  id="un-select" style="font-weight: bold;" class="control-label">Unselect All Permissions</label>



                                                     @foreach ($permissions as $permission)
                                              <ul class="list-unstyled ">
                                              <li>
                                                        <input  type="checkbox"  name="title[]" value="{{$permission->id}}" > <span class="checkmark"></span>{{ $permission->title  }}
                                                        </li>
                                                        </ul>
                                                        @endforeach
                                                @if($errors->first('title'))
                                                <div class="form-control-feedback">{{ $errors->first('title') }}
                                                </div>
                                                @endif
                                        </div>


                                </div>
                                <div class="tile-footer">
                                        <button class="btn btn-primary" type="submit"><i
                                                        class="fa fa-fw fa-lg fa-check-circle"></i> Save Record</button>
                                </div>
                        </div>
                </div>
        </div>
</form>




@endsection
@section('scripts')
<script>
$(document).ready(function(){
$("#un-select").hide();
});
$('#select-all').click(function(event) {
    if(this.checked) {
        // Iterate each checkbox
        $(':checkbox').each(function() {
            this.checked = true;
            $("#select").hide();
            $("#un-select").show();
        });
    } else {
        $(':checkbox').each(function() {
            this.checked = false;
            $("#un-select").hide();
            $("#select").show();


        });
    }
});
</script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="app-title">
        <div>
                <h1><i class="fa fa-edit"></i> User</h1>
        </div>
</div>
<form method="post" action="{{action('Permission\PermissionController@update',$id)}}">
        <div class="row">
                <div class="col-md-6">
                        <div class="tile">
                                <h3 class="tile-title">Edit User</h3>
                                <div class="tile-body">
                                        @if($errors->all())
                                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                <strong>Please fix below errors</strong>
                                                <button type="button" class="close" data-dismiss="alert"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                </button>
                                        </div>
                                        @endif
                                        {{csrf_field()}}
                                        <input name="_method" type="hidden" value="PATCH">
                                        <input type="hidden" value="{{csrf_token()}}" name="_token" />

                                        <div class="form-group">
                                                <label class="control-label">Name</label>
                                                <input class="{{ $errors->first('name') != '' ? 'form-control is-invalid' : 'form-control' }}"
                                                        type="text" placeholder="Enter User Name"
                                                        name="name" value="{{$user->name}}" required>
                                                @if($errors->first('name'))
                                                <div class="form-control-feedback">{{ $errors->first('name') }}
                                                </div>
                                                @endif
                                        </div>

                                     <div class="form-group">
                                     <label class="control-label">Email</label>
                                          <input class="{{ $errors->first('email') != '' ? 'form-control is-invalid' : 'form-control' }}" type="email"
                                              placeholder="Email" autofocus name="email" value="{{$user->email }}" required>
                                                  @if($errors->first('email'))
                                                <div class="form-control-feedback">{{ $errors->first('email') }}</div>
                                                     @endif
                                                    </div>
                                                     </div>




                                          <div class="form-group">
                                                <input type="checkbox"   name="select-all" id="select-all" />

                                                <label id="select" style="font-weight: bold;"  class="control-label ">Select All Permissions</label>
                                                <label  id="un-select" style="font-weight: bold;" class="control-label">Unselect All Permissions</label>


                                                     @foreach ($permissions as $permission)
                                              <ul class="list-unstyled">
                                              <li>
                                                        <input type="checkbox"  name="title[]"  value="{{$permission->id}}"  {{ ($permission->status=='true') ? "checked" : "" }} >{{ $permission->title  }}
                                                        </li>
                                                        </ul>
                                                        @endforeach
                                                @if($errors->first('title'))
                                                <div class="form-control-feedback">{{ $errors->first('title') }}
                                                </div>
                                                @endif
                                        </div>


                                </div>
                                <div class="tile-footer">
                                        <button class="btn btn-primary" type="submit"><i
                                                        class="fa fa-fw fa-lg fa-check-circle"></i> Update Record</button>
                                </div>
                        </div>
                </div>
        </div>
</form>




@endsection
@section('scripts')
<script>
$(document).ready(function(){
$("#un-select").hide();
});
$('#select-all').click(function(event) {
    if(this.checked) {
        // Iterate each checkbox
        $(':checkbox').each(function() {
            this.checked = true;
            $("#select").hide();
            $("#un-select").show();

        });
    } else {
        $(':checkbox').each(function() {
            this.checked = false;
            $("#un-select").hide();
            $("#select").show();


        });
    }
});
</script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.master')
@section('title', 'User')
@section('search')
<li class="app-search">
  <form action="{{action('User\UserController@search')}}" method="POST">
    <input type="hidden" value="{{csrf_token()}}" name="_token" />
    <input class="app-search__input" name="search" type="search" placeholder="Search" value="{{ $search ?? '' }}">
    <button class="app-search__button" type="submit"><i class="fa fa-search"></i></button>
  </form>
</li>
@endsection
@section('content')
<div class="app-title">
    <div>
        <h1><i class="fa fa-th-list"></i> User</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                @if(session('message'))
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ session('message') }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif

                <div style="float:right; padding: 10px;">
                <a href="{{action('User\UserController@create')}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-plus"></i> Add
                                    </a>
                                    </div>

                <table class="table table-hover table-bordered" id="sampleTable">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (count($users) > 0)
                        @foreach ($users as $user)
                        <tr>
                            <td>{{ $user->name }}</td>
                            <td>{{$user->email}} </td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a href="{{action('User\UserController@edit',$user->id)}}"
                                        class="btn btn-sm btn-primary">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                       <a href="{{ route('user.destroy', $user->id) }}"
                                        class="confirmation btn btn-sm btn-danger" data-title="Delete Record"
                                        data-text="Are you sure to delete this record and its associated data? ">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                         @else
                                                <tr>
                                                <td colspan="6" class="text-center">
                                                        No Record Found
                                                </td>
                                                </tr>
                                                @endif
                    </tbody>
                </table>
                {{ $users->links() }}
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<!-- Page specific javascripts-->
<script>
    jQuery(document).on('click', '.confirmation', function (e) {
    e.preventDefault(); // Prevent the href from redirecting
    var linkURL = $(this).attr("href");
    var _title = $(this).attr("data-title");
    var _text = $(this).attr("data-text");
    warnBeforeRedirect(linkURL, _text, _title);
});

function warnBeforeRedirect(linkURL, _text, _title) {

    swal({
  title: _title,
  text: _text,
  type: "warning",
  icon: "warning",
  dangerMode: true,
  buttons: true,
}).then(function(isConfirm) {
  if(isConfirm){
 var form = $('<form>', {
            'method': 'POST',
            'action': linkURL
        });

        var hiddenInput = $('<input>', {
            'name': '_method',
            'type': 'hidden',
            'value': 'DELETE'
        });

        hiddenToken = $('<input>', {
            'name': '_token',
            'type': 'hidden',
            'value': jQuery('meta[name="csrf-token"]').attr('content')
        });

        form.append(hiddenInput).append(hiddenToken).appendTo('body').submit();
}else {
    swal("Cancelled", "Your record is safe :)", "info");
  }
});
}
</script>
@endsection